### ISSUE TITLE
Create escalation router custom setting and auto assign owner on insert

### ISSUE THREAD

**Issue by pcon** [RedHatSalesforce/escalations#13]
Create a custom setting called `EscalationRouter__c`that has the following fields

* `Name` - (default field) - This is the escalation record type name
* `DefaultOwner__c` - String - This is the Id of the User to assign ownership of the escalation on insert.

In addition to creating this custom setting, update the `EscalationTrigger` to pull down the route for the record type and the assign the `OwnerId` field based on the `DefaultOwner__c`

**Comment by preeti-preeti** [comment]
@pcon I think this should be either implemented in escalations-impl package or in CCM, as in this package we do not have any recordType available for escalation.
My other concern is: 
In impl package we do not have any trigger written for escalations, so should we implement this in CCM?

**Comment by preeti-preeti** [comment]
@pcon, I am not sure if i get u properly here or not. 
What I understood is we have to assign a default owner based upon recordType name present in custom setting. 
So, in custom setting we will have two records one for ACE and another for CFE and then we will fetch custom setting based upon escalation recordType. Something like this : http://pastebin.test.redhat.com/484064 . If we have to implement something like above then we should have at-least one recordType.
 
Secondly we can have a single data for all recordTypes and the defaultOwner present in custom setting will be assigned to the escalation irrespective of recordType? 
Please suggest what should be our approach for this?

**Comment by pcon** [comment]
Actually having record types in the base package is not needed and would only be required for the apex tests.  If we wanted to have a catch all, then I would propose that we have a reserved name for the custom setting that would do this.  So for example, the router custom setting with the name `DEFAULT` would apply to all escalations regardless of record type assuming that `recordType.Name` does not exist in the router name list.
