### ISSUE TITLE
Add new dateTime field  for tracking status change date and update the trigger logic for the same.

### ISSUE THREAD

**Issue by preeti-preeti** [RedHatSalesforce/escalations#19]

**Comment by preeti-preeti** [comment]
@pcon rh_escalImpl__Status__c is present in impl  package, so I think the new field 'Status Changed On' should be added to impl package and the logic should be handled in CCM escalationtrigger.

Whats your opinion on this?

**Comment by pcon** [comment]
The field and the trigger logic should both live in the impl package and not in the base package.
